site_name: Checkers
theme:
  name: gitbook

repo_name: checkers
repo_url: https://github.com/seastar-consulting/checkers

nav:
  - Home: index.md
  - Getting Started: getting-started.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
