title: Checkers
description: A diagnostics framework for developer workstations
theme: just-the-docs

url: https://seastar-consulting.github.io/checkers

aux_links:
  "Checkers on GitHub":
    - "https://github.com/seastar-consulting/checkers"

# Footer content
footer_content: "Copyright &copy; 2025 seastar consulting. Distributed under the Apache License 2.0."

# Enable or disable the site search
search_enabled: true

# Set the search token separator
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Enable or disable heading anchors
heading_anchors: true

# Sort order for navigation links
nav_sort: case_sensitive

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Color scheme supports "light" (default) and "dark"
color_scheme: light

# Footer metadata
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y"

footer_links:
  "seastar consulting":
    - "https://seastar.consulting"
